theme: jekyll-theme-slate
title: [Chris Newton]
![VegSoc logo](https://raw.githubusercontent.com/ChrisDNewton/ChrisDNewton.github.io/master/VEG_SOC_MASTER_FULL_COL_RGB_-300x179.jpg)
description: [PhD student in Data Analytics and Society at the University of Manchester]
