theme: jekyll-theme-minimal
title: [Chris Newton]
description: [PhD student in Data Analytics and Society at the University of Manchester]
<!-- I would like to add a picture in here... current one is just a placeholder. -->
![VegSoc logo](https://raw.githubusercontent.com/ChrisDNewton/ChrisDNewton.github.io/master/VEG_SOC_MASTER_FULL_COL_RGB_-300x179.jpg)
